"use strict";
exports.__esModule = true;
var child_process_1 = require("child_process");
var fs = require("fs-extra");
var path = require("path");
var stripJsonComments = require("strip-json-comments");
var tsConfigPath = path.join(process.cwd(), '/tsconfig.json');
var packagePath = path.join(process.cwd(), '/package.json');
var readmePath = path.join(process.cwd(), '/README.md');
var licensePath = path.join(process.cwd(), '/LICENSE');
var tsContentContents = stripJsonComments(fs.readFileSync(tsConfigPath, { encoding: 'utf8' }), { whitespace: true });
var tsconfigJSON = JSON.parse(tsContentContents);
var packageContentContents = stripJsonComments(fs.readFileSync(packagePath, { encoding: 'utf8' }), { whitespace: true });
var packageJSON = JSON.parse(packageContentContents);
var licenseContents = fs.readFileSync(path.join(__dirname, '/LICENSE'), { encoding: 'utf8' });
tsconfigJSON.include = ["src/**/*.ts"];
tsconfigJSON.lib = ["es2017", "dom"];
tsconfigJSON.compilerOptions.resolveJsonModule = true;
fs.writeFileSync(tsConfigPath, JSON.stringify(tsconfigJSON, null, 4), { encoding: 'utf8' });
packageJSON.scripts.test = "mocha -r ts-node/register tests/**/*.ts";
packageJSON.main = "src/main.ts";
var username = child_process_1.execSync("git config --global user.name", { encoding: 'utf8' }).trim().replace('\n', "");
var email = child_process_1.execSync("git config --global user.email", { encoding: 'utf8' }).trim().replace('\n', "");
packageJSON.author = username + " <" + email + ">";
fs.writeFileSync(packagePath, JSON.stringify(packageJSON, null, 4), { encoding: 'utf8' });
fs.writeFileSync(readmePath, "# " + packageJSON.name + "\n\n" + packageJSON.description + "\n\nAuthor " + packageJSON.author + "\n\nCreated " + new Date().toString(), { encoding: 'utf8' });
fs.writeFileSync(licensePath, licenseContents, { encoding: 'utf8' });
console.log(tsconfigJSON);
